create extension if not exists pgtap with schema extensions;
set search_path to public,extensions;
begin;
select plan(30);

select has_table('public','profiles','profiles exists');
select has_table('public','activities','activities exists');
select has_table('public','friendships','friendships exists');
select has_table('public','fyrups','fyrups exists');
select has_table('public','session_invites','invites exists');
select has_table('public','notification_preferences','notification preferences exist');
select has_column('public','planned_sessions','place_name','planned session place exists');
select has_index('public','activities','one_live_activity_per_user','only one LIVE activity is enforced');
select has_index('public','fyrups','fyrups_sender_id_recipient_id_sender_local_date_key','daily FYR UP uniqueness is enforced');
select policies_are('public','profiles',array['profiles_read','profiles_insert','profiles_update'],'profile RLS policies');
select policies_are('public','notifications',array['notifications_read'],'notification RLS policies');
select policies_are('public','device_tokens',array['tokens_owner'],'token RLS policy');
select policies_are('public','notification_preferences',array['notification_preferences_owner'],'notification preference RLS policy');
select ok(exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars_insert_own'),'avatar owner insert policy');
select ok(exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars_update_own'),'avatar owner update policy');
select ok(exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars_delete_own'),'avatar owner delete policy');
select ok(exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars_read_self_or_friends'),'avatar private read policy');
select has_function('public','send_friend_request',array['uuid'],'friend request RPC exists');
select has_function('public','answer_friend_request',array['uuid','boolean'],'friend answer RPC exists');
select has_function('public','block_user',array['uuid'],'block RPC exists');
select has_function('public','start_activity',array['sport_kind','text','uuid','uuid'],'activity start RPC exists');
select has_function('public','complete_activity',array['uuid','integer'],'activity completion RPC exists');
select has_function('public','plan_session',array['sport_kind','text','timestamp with time zone','smallint','text','text','boolean','uuid[]'],'planning RPC exists');
select has_function('public','update_planned_session',array['uuid','timestamp with time zone','smallint','text','text','boolean'],'planned session update RPC exists');
select has_function('public','my_hosted_sessions',array[]::text[],'hosted session details RPC exists');
select has_function('public','send_fyrup',array['uuid','text'],'FYR UP RPC exists');
select has_function('public','respond_to_invite',array['uuid','invitation_status'],'invitation answer RPC exists');
select has_function('public','cancel_session',array['uuid'],'host cancellation RPC exists');
select has_function('public','get_notification_preferences',array[]::text[],'notification preference read RPC exists');
select has_function('public','save_notification_preferences',array['boolean','boolean','boolean','boolean','boolean','boolean','boolean','boolean'],'notification preference save RPC exists');

select * from finish();
rollback;
