create extension if not exists pgtap with schema extensions;
set search_path to public,extensions;
begin;
select no_plan();
insert into auth.users values ('ac130000-0000-0000-0000-000000000001'),('ac130000-0000-0000-0000-000000000002');
insert into public.profiles(id,username,display_name) values
 ('ac130000-0000-0000-0000-000000000001','qa_supp_one','Supplement One'),
 ('ac130000-0000-0000-0000-000000000002','qa_supp_two','Supplement Two');
insert into public.friendships(requester_id,addressee_id,status) values ('ac130000-0000-0000-0000-000000000001','ac130000-0000-0000-0000-000000000002','accepted');
select ok(relrowsecurity,'RLS enabled: '||relname) from pg_class where oid in ('public.supplement_settings'::regclass,'public.supplement_plans'::regclass,'public.supplement_doses'::regclass,'public.supplement_receipts'::regclass,'public.supplement_reminder_jobs'::regclass);
select ok(not has_table_privilege('authenticated',t,p),'direct mutation denied: '||t||' '||p) from unnest(array['public.supplement_settings','public.supplement_plans','public.supplement_doses','public.supplement_receipts','public.supplement_reminder_jobs']) t cross join unnest(array['insert','update','delete']) p;
select ok(not has_table_privilege('authenticated',t,'select'),'internal table denied: '||t) from unnest(array['public.supplement_receipts','public.supplement_reminder_jobs']) t;
select ok(not has_function_privilege('anon',f,'execute'),'anonymous RPC denied: '||f) from unnest(array['public.get_supplements(text)','public.save_supplement_plan(jsonb)','public.save_supplement_settings(jsonb)','public.set_supplement_dose(jsonb)']) f;
select ok(not has_function_privilege(r,f,'execute'),'client cannot schedule/send: '||r||' '||f) from unnest(array['anon','authenticated']) r cross join unnest(array['public.materialize_supplement_day(uuid,timestamptz)','public.process_supplement_reminders(timestamptz)','public.can_dispatch_supplement(uuid,timestamptz)']) f;
select ok(has_function_privilege('service_role',f,'execute'),'server scheduler authorized: '||f) from unnest(array['public.process_supplement_reminders(timestamptz)','public.can_dispatch_supplement(uuid,timestamptz)']) f;
create temporary table qa_supp(k text primary key,v jsonb); grant all on qa_supp to authenticated;
insert into qa_supp values('plan','{"id":"ac131000-0000-0000-0000-000000000001","owner_id":"AC130000-0000-0000-0000-000000000001","revision":0,"name":"  My own entry  ","weekdays":[1,2,3,4,5,6,7],"slots":[{"id":"ac132000-0000-0000-0000-000000000001","minute":540}],"is_paused":false,"is_archived":false,"reminders_enabled":true,"repeat_minutes":30,"repeat_count":2}');
set local role authenticated;
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select public.get_supplements('UTC')$$,'P0001','unauthorized','no-session read rejected');
select throws_ok($$select public.save_supplement_plan((select v from qa_supp where k='plan'))$$,'P0001','unauthorized','no-session save rejected');
select set_config('request.jwt.claim.sub','ac130000-0000-0000-0000-000000000001',true);
select throws_ok($$select public.get_supplements('Invalid/Zone')$$,'P0001','invalid_timezone','unknown timezone rejected');
select throws_ok($$select public.save_supplement_plan((select v from qa_supp where k='plan'))$$,'P0001','settings_required','schedule needs an explicit zone first');
insert into qa_supp values('initial',public.get_supplements('UTC'));
select is((select v->'plans' from qa_supp where k='initial'),'[]'::jsonb,'no products or suggested intakes seeded');
select is((select v->'doses' from qa_supp where k='initial'),'[]'::jsonb,'empty setup has no artificial dose');
select is(public.get_supplements('Europe/Berlin')#>>'{settings,timezone}','UTC','system timezone change does not change saved intake day');
select throws_ok($$select public.save_supplement_plan(null)$$,'P0001','invalid_supplement','null plan rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"name":""}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','empty name rejected');
select throws_ok($$select public.save_supplement_plan(v||jsonb_build_object('name',repeat('x',61))) from qa_supp where k='plan'$$,'P0001','invalid_supplement','oversized name rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"revision":"0"}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','string revision rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"weekdays":[]}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','no weekday rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"weekdays":[1,1]}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','duplicate weekdays rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"weekdays":[0]}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','weekday zero rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"weekdays":["1"]}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','string weekday rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"slots":[]}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','no time rejected');
select throws_ok($$select public.save_supplement_plan(jsonb_set(v,'{slots,0,minute}','1440')) from qa_supp where k='plan'$$,'P0001','invalid_supplement','out of range time rejected');
select throws_ok($$select public.save_supplement_plan(jsonb_set(v,'{slots,0,minute}','-1')) from qa_supp where k='plan'$$,'P0001','invalid_supplement','negative time rejected');
select throws_ok($$select public.save_supplement_plan(jsonb_set(v,'{slots,0,minute}','"540"')) from qa_supp where k='plan'$$,'P0001','invalid_supplement','string time rejected');
select throws_ok($$select public.save_supplement_plan(v||jsonb_build_object('slots',(v->'slots')||(v->'slots'))) from qa_supp where k='plan'$$,'P0001','invalid_supplement','duplicate slot rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"repeat_count":4}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','unbounded repeat rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"repeat_minutes":1}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','excessive cadence rejected');
select throws_ok($$select public.save_supplement_plan(v||'{"owner_id":"ac130000-0000-0000-0000-000000000002"}') from qa_supp where k='plan'$$,'P0001','invalid_supplement','another owner rejected');
insert into qa_supp values('saved',public.save_supplement_plan((select v from qa_supp where k='plan')));
select is((select v->>'revision' from qa_supp where k='saved'),'1','uppercase native UUID accepted and revision confirmed');
select is((select v->>'name' from qa_supp where k='saved'),'My own entry','name normalized');
select throws_ok($$select public.save_supplement_plan((select v from qa_supp where k='plan'))$$,'P0001','supplement_conflict','stale plan cannot overwrite confirmed state');
select is(jsonb_array_length(public.get_supplements('UTC')->'doses'),1,'exactly one daily slot materialized');
select is(jsonb_array_length(public.get_supplements('UTC')->'doses'),1,'repeated reads never duplicate daily intake');
insert into qa_supp values('dose',public.get_supplements('UTC')#>'{doses,0}');
insert into qa_supp values('take',jsonb_build_object('request_id','ac133000-0000-0000-0000-000000000001','dose_id',(select v->>'id' from qa_supp where k='dose'),'status','taken','expected_revision',1));
select is(public.set_supplement_dose((select v from qa_supp where k='take'))->>'status','taken','taking confirms one dose');
select is(public.set_supplement_dose((select v from qa_supp where k='take'))->>'revision','2','retry with same request never counts twice');
select throws_ok($$select public.set_supplement_dose(v||'{"status":"skipped"}') from qa_supp where k='take'$$,'P0001','supplement_request_conflict','request ID cannot be reused with changed content');
select throws_ok($$select public.set_supplement_dose(v||'{"request_id":"ac133000-0000-0000-0000-000000000002","status":"open"}') from qa_supp where k='take'$$,'P0001','supplement_conflict','stale undo rejected');
select is(public.set_supplement_dose((select v||'{"request_id":"ac133000-0000-0000-0000-000000000002","status":"open","expected_revision":2}' from qa_supp where k='take'))->>'revision','3','explicit current undo works');
select is(public.set_supplement_dose((select v from qa_supp where k='take'))->>'status','open','old successful retry returns current status without retaking');
select is(public.set_supplement_dose((select v||'{"request_id":"ac133000-0000-0000-0000-000000000003","status":"skipped","expected_revision":3}' from qa_supp where k='take'))->>'status','skipped','skip is distinct from taken');
select is(public.save_supplement_plan((select v||'{"name":"Renamed"}' from qa_supp where k='saved'))->>'revision','2','plan can be edited');
select is(public.get_supplements('UTC')#>>'{doses,0,status}','skipped','editing name never resets a closed dose');
select throws_ok($$select public.save_supplement_settings('{"revision":1,"timezone":"Europe/Berlin","quiet_enabled":true,"quiet_start":1320,"quiet_end":480}')$$,'P0001','supplement_timezone_fixed','explicit timezone change also cannot create duplicate day');
select throws_ok($$select public.save_supplement_settings('{"revision":1,"timezone":"UTC","quiet_enabled":true,"quiet_start":0,"quiet_end":0}')$$,'P0001','invalid_supplement_settings','ambiguous all-day quiet rejected');
select lives_ok($$select public.save_supplement_settings('{"revision":1,"timezone":"UTC","quiet_enabled":false,"quiet_start":1320,"quiet_end":480}')$$,'quiet hours can be explicitly disabled');
select throws_ok($$select public.save_supplement_settings('{"revision":1,"timezone":"UTC","quiet_enabled":true,"quiet_start":1320,"quiet_end":480}')$$,'P0001','supplement_conflict','stale settings cannot overwrite');
select set_config('request.jwt.claim.sub','ac130000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.supplement_settings),0::bigint,'even accepted friends cannot read settings');
select is((select count(*) from public.supplement_plans),0::bigint,'even accepted friends cannot read plans');
select is((select count(*) from public.supplement_doses),0::bigint,'even accepted friends cannot read intakes');
select throws_ok($$select public.set_supplement_dose((select v from qa_supp where k='take'))$$,'P0001','unauthorized','cannot acknowledge another person dose');
select lives_ok($$select public.get_supplements('Europe/Berlin')$$,'second account has own independent timezone');
select throws_ok($$select public.save_supplement_plan(v||'{"owner_id":"ac130000-0000-0000-0000-000000000002","revision":2}') from qa_supp where k='saved'$$,'P0001','unauthorized','plan ID cannot be hijacked by another account');
reset role;

-- Server clock fixtures: future days do not depend on wall-clock time of this test run.
select is(public.process_supplement_reminders('2030-01-07 08:59Z'),0,'nothing sent before slot');
select is(public.process_supplement_reminders('2030-01-07 09:00Z'),1,'initial reminder generated');
select is(public.process_supplement_reminders('2030-01-07 09:00Z'),0,'overlapping cron is idempotent');
insert into qa_supp values('notification',to_jsonb((select notification_id from public.supplement_reminder_jobs j join public.supplement_doses d on d.id=j.dose_id where d.day='2030-01-07' and j.ordinal=0)));
select ok(public.can_dispatch_supplement((select (v#>>'{}')::uuid from qa_supp where k='notification'),'2030-01-07 09:01Z'),'authorized pending dose allowed just before send');
select ok(not public.can_dispatch_supplement((select (v#>>'{}')::uuid from qa_supp where k='notification'),'2030-01-07 08:59Z'),'clock rollback cannot send before due');
select ok(not public.can_dispatch_supplement((select (v#>>'{}')::uuid from qa_supp where k='notification'),'2030-01-07 09:05Z'),'reminder expires at five minutes');
select is(public.process_supplement_reminders('2030-01-07 09:30Z'),1,'one selected repeat generated');
select is(public.process_supplement_reminders('2030-01-07 10:00Z'),1,'last selected repeat generated');
select is(public.process_supplement_reminders('2030-01-07 10:30Z'),0,'no repeat beyond chosen cap');
select is(public.process_supplement_reminders('2030-01-08 09:36Z'),0,'outage never creates a catch-up burst');
select is(public.process_supplement_reminders('2030-01-08 10:02Z'),1,'only latest still-relevant repeat after outage');
select is((select count(*) from public.supplement_reminder_jobs j join public.supplement_doses d on d.id=j.dose_id where d.day='2030-01-08'),1::bigint,'earlier missed repeats not backfilled');
select ok(not exists(select 1 from public.notifications where type='supplement_reminder' and (title like '%Renamed%' or body like '%Renamed%' or data::text like '%Renamed%')),'lock-screen preview never contains supplement names');
update public.supplement_doses set status='taken',revision=revision+1,changed_at=now() where day='2030-01-07';
select ok(not public.can_dispatch_supplement((select (v#>>'{}')::uuid from qa_supp where k='notification'),'2030-01-07 09:01Z'),'acknowledgement on another device suppresses previously queued reminder');
select is(public.process_supplement_reminders('2030-01-07 09:30Z'),0,'taken dose never requeued');
update public.supplement_settings set quiet_enabled=true,quiet_start=540,quiet_end=600 where owner_id='ac130000-0000-0000-0000-000000000001';
select is(public.process_supplement_reminders('2030-01-09 09:00Z'),0,'quiet starts inclusively');
select is(public.process_supplement_reminders('2030-01-09 09:30Z'),0,'quiet repeat skipped');
select is(public.process_supplement_reminders('2030-01-09 10:00Z'),1,'quiet ends exclusively');
select ok(public.supplement_is_quiet(1380,true,1320,480),'overnight quiet late evening');
select ok(public.supplement_is_quiet(0,true,1320,480),'overnight quiet past midnight');
select ok(not public.supplement_is_quiet(480,true,1320,480),'overnight quiet end exclusive');
select ok(not public.supplement_is_quiet(1380,false,1320,480),'disabled quiet does not suppress');
update public.supplement_plans set is_paused=true where id='ac131000-0000-0000-0000-000000000001';
select is(public.process_supplement_reminders('2030-01-10 09:00Z'),0,'paused plan does not enqueue');
select ok(not public.can_dispatch_supplement((select (v#>>'{}')::uuid from qa_supp where k='notification'),'2030-01-07 09:01Z'),'paused plan cannot dispatch');
update public.supplement_plans set is_paused=false,is_archived=true where id='ac131000-0000-0000-0000-000000000001';
select is(public.process_supplement_reminders('2030-01-10 10:00Z'),0,'archived plan does not enqueue');
update public.supplement_plans set is_archived=false,reminders_enabled=false where id='ac131000-0000-0000-0000-000000000001';
select is(public.process_supplement_reminders('2030-01-10 10:00Z'),0,'disabled reminders do not enqueue');
select throws_ok($$select public.process_supplement_reminders('infinity')$$,'P0001','invalid_supplement_time','infinite server clock rejected');
select throws_ok($$select public.materialize_supplement_day('ac130000-0000-0000-0000-000000000001',null)$$,'P0001','invalid_supplement_time','null server clock rejected');

-- Two occurrences of 02:30 on the autumn clock change still mean one authored slot.
update public.supplement_settings set timezone='Europe/Berlin' where owner_id='ac130000-0000-0000-0000-000000000001';
update public.supplement_plans set slots='[{"id":"ac132000-0000-0000-0000-000000000001","minute":150}]' where id='ac131000-0000-0000-0000-000000000001';
select public.materialize_supplement_day('ac130000-0000-0000-0000-000000000001','2026-10-25 00:30Z');
select public.materialize_supplement_day('ac130000-0000-0000-0000-000000000001','2026-10-25 01:30Z');
select is((select count(*) from public.supplement_doses where day='2026-10-25'),1::bigint,'DST fall-back creates only one dose for same slot');
select is((select due_at from public.supplement_doses where day='2026-10-25'),'2026-10-25 01:30Z'::timestamptz,'ambiguous time consistently uses standard offset');
select public.materialize_supplement_day('ac130000-0000-0000-0000-000000000001','2026-03-29 01:30Z');
select is((select due_at from public.supplement_doses where day='2026-03-29'),'2026-03-29 01:30Z'::timestamptz,'missing spring hour resolves forward consistently');
select is((select count(*) from public.weekly_activity_credits where user_id='ac130000-0000-0000-0000-000000000001'),0::bigint,'supplements never add workout or streak credit');
select ok(not has_function_privilege('anon','public.bind_device_token(text,text,uuid)','execute'),'anonymous token binding denied');
select ok(not has_function_privilege('anon','public.unregister_device_token(text,uuid)','execute'),'anonymous token detach denied');
set local role authenticated;
select set_config('request.jwt.claim.sub','ac130000-0000-0000-0000-000000000001',true);
select throws_ok($$select public.bind_device_token(repeat('a',64),'ios','ac130000-0000-0000-0000-000000000002')$$,'P0001','unauthorized','registration rejects stale expected account');
select throws_ok($$select public.bind_device_token('not a token','ios','ac130000-0000-0000-0000-000000000001')$$,'P0001','invalid_device_token','invalid token rejected');
select ok(public.bind_device_token(repeat('a',64),'ios','ac130000-0000-0000-0000-000000000001'),'own device registered');
select set_config('request.jwt.claim.sub','ac130000-0000-0000-0000-000000000002',true);
select ok(public.bind_device_token(repeat('a',64),'ios','ac130000-0000-0000-0000-000000000002'),'same installation claimed by its new account');
reset role;
select is((select count(*) from public.device_tokens where token=repeat('a',64)),1::bigint,'one installation is not sent both accounts notifications');
select is((select user_id::text from public.device_tokens where token=repeat('a',64)),'ac130000-0000-0000-0000-000000000002','binding belongs to new account');
set local role authenticated;
select set_config('request.jwt.claim.sub','ac130000-0000-0000-0000-000000000001',true);
select ok(public.unregister_device_token(repeat('a',64),'ac130000-0000-0000-0000-000000000001'),'old logout is harmless and idempotent');
select throws_ok($$select public.unregister_device_token(repeat('a',64),'ac130000-0000-0000-0000-000000000002')$$,'P0001','unauthorized','old account cannot remove a new owner binding');
reset role;
select is((select count(*) from public.device_tokens where token=repeat('a',64)),1::bigint,'late old logout preserves new account push binding');
select * from finish();
rollback;
